### ISSUE TITLE
support API level 7

### ISSUE THREAD

**Issue by JoachimR** [martin-stone/hsv-alpha-color-picker-android#14]
Hi,

is there a specific reason you only support api lvl 11 ? 

I am looking for a picker that can be used in the android.support.v7.preference.Preference that also works for API level 7.

Thanks in advance and great work

**Comment by martin-stone** [comment]
Is there a specific reason you want to support 7? The number of devices below 11 is tiny. 

I'm hesitant to drop any lower, because it's harder to go back up again if I want to use a more recent API. 

There's nothing stopping you cloning the library and changing your copy, though: There are a couple of level 8 calls in the code that are easily replaced. Also, I think you'd need to modify it anyway if you wanted to switch to using the support preference. (I prefer to keep the library free of unnecessary dependencies.)
