### ISSUE TITLE
Still a long delay when opening preference on Nexus 7 for the first time

### ISSUE THREAD

**Issue by aloz77** [martin-stone/hsv-alpha-color-picker-android#38]
#28 is living again in the library 2.2.0

**Comment by martin-stone** [comment]
OK. I'll look into it.

**Comment by james-s-w-clark** [comment]
Getting ~150 frames skipped when opening the color-picker for the first time.

**Comment by martin-stone** [comment]
The library generates the Hue/Sat bitmap the first time the picker is shown, matching the size of the view. The size should probably be limited to 256 square, and maybe baked-in as a resource instead of generated.

I'd be happy to consider a PR that does that. Otherwise it'll have to wait until I have some free time.

**Comment by martin-stone** [comment]
I've released version 2.3, which limits the bitmap size and is much faster.
